const imageUrl = 'https://cityview.s3.us-west-004.backblazeb2.com'
const noImage =
  'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png'

export const categories = [
  { name: 'Hot Dishes', slug: 'hot-dishes' },
  { name: 'Appetizers', slug: 'appetizers' },
  { name: 'Barbecue Dishes', slug: 'barbecue-dishes' },
  { name: 'Main Dishes (Chicken)', slug: 'main-dishes-chicken' },
  { name: 'Main Dishes (Lamb)', slug: 'main-dishes-lamb' },
  { name: 'Sea Food', slug: 'sea-food' },
  { name: 'Arabian Bread', slug: 'arabian-bread' },
  { name: 'Hot Soups', slug: 'hot-soups' },
  { name: 'Sandwiches', slug: 'sandwiches' },
  { name: 'Beverages', slug: 'beverages' },
  { name: 'Fresh Juices', slug: 'fresh-juices' },
  { name: 'Desserts', slug: 'desserts' },
  { name: 'Coffee', slug: 'coffee' },
  { name: 'Ice Cream', slug: 'ice-cream' },
  { name: 'Pies & Pastry', slug: 'pies-pastry' },
  { name: 'Snacks', slug: 'snacks' },
  { name: 'Burgers', slug: 'burgers' },
  { name: 'Pizza', slug: 'pizza' },
  { name: 'Indian Food', slug: 'indian-food' },
  { name: 'Chapati', slug: 'chapati' },
  { name: 'Curry', slug: 'curry' },
  { name: 'Side Dish', slug: 'side-dish' },
  { name: 'Sweet', slug: 'sweet' },
  { name: 'Ethiopian Food', slug: 'ethiopian-food' },
  { name: 'Breakfast', slug: 'breakfast' },
  { name: 'Special Order', slug: 'special-order' },
]

export const items = [
  {
    categorySlug: 'hot-dishes',
    name: 'FAHSAH LAMB',
    price: 8,
    image: `${imageUrl}/DSC_7564.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'TUNA FAHSAH',
    price: 7,
    image: `${imageUrl}/DSC_7613.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'SALTAH',
    price: 5,
    image: `${imageUrl}/DSC_7613.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'FRIED LAMB MEAT (MOKALKAL)',
    price: 5,
    image: `${imageUrl}/DSC_7445.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'FRIED LAMB MEAT',
    price: 6,
    image: `${imageUrl}/DSC_7629.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'OQDA LAMB',
    price: 7,
    image: `${imageUrl}/DSC_7409.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'FRIED LAMB LIVER',
    price: 5,
    image: `${imageUrl}/DSC_7494.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'MOLOKHIA (JUTE LEAVES) WITH MEAT',
    price: 4,
    image: `${imageUrl}/DSC_7687.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'LADIES FINGERS WITH LAMB',
    price: 5,
    image: `${imageUrl}/DSC_9729.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'FRIED MEAT KUBA',
    price: 5,
    image: `${imageUrl}/DSC_7655.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'CHICKEN FAHSAH',
    price: 7,
    image: `${imageUrl}/DSC_7664.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'FRIED CHICKEN (MOKALKAL)',
    price: 6,
    image: `${imageUrl}/DSC_7537.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'MOLOKHIA (JUTE LEAVES) WITH CHICKEN',
    price: 4,
    image: `${imageUrl}/DSC_7687.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'LADIES FINGERS WITH CHICKEN',
    price: 4,
    image: `${imageUrl}/283A0237.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'LADIES FINGERS',
    price: 3,
    image: `${imageUrl}/283A0227.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'MOLOKHIA (JUTE LEAVES)',
    price: 3,
    image: `${imageUrl}/DSC_7676.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'VEGETABLE HOT DISH WITH RICE',
    price: 2,
    image: `${imageUrl}/283A0230.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'VEGETABLE HOT DISH',
    price: 4,
    image: `${imageUrl}/283A0230.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'DRY WHITE BEAN WITH EGG',
    price: 5,
    image: `${imageUrl}/DSC_7379.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'DRY WHITE BEAN',
    price: 3,
    image: `${imageUrl}/DSC_7379.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'FOUL (RED BEANS)',
    price: 3,
    image: `${imageUrl}/DSC_7631(1).JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'SHAKSHOUKA EGG',
    price: 3,
    image: `${imageUrl}/DSC_7385.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'COOKED EGGS EYE SHAPED',
    price: 3,
    image: `${imageUrl}/DSC_7701.JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'FRIED EGGS',
    price: 3,
    image: `${imageUrl}/DSC_7717(1).JPG`,
  },
  {
    categorySlug: 'hot-dishes',
    name: 'FALAFEL',
    price: 3,
    image: `${imageUrl}/DSC_7637.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'ROYAL HADRAMAWT MIX APPETIZERS (LARGE)',
    price: 8,
    image: `${imageUrl}/DSC_6229.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'ROYAL HADRAMAWT MIX APPETIZERS (REGULAR)',
    price: 6,
    image: `${imageUrl}/DSC_6229.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'ARABIC SALAD',
    price: 3,
    image: `${imageUrl}/DSC_6097.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'STUFFED GRAPE LEAVES',
    price: 5,
    image: `${imageUrl}/DSC_6086.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'PICKLED',
    price: 2,
    image: `${imageUrl}/DSC_9685.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'FATTOUSH',
    price: 3,
    image: `${imageUrl}/DSC_6060.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'OLIVES SALAD',
    price: 5,
    image: `${imageUrl}/DSC_6169.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'TABBOULEH',
    price: 5,
    image: `${imageUrl}/DSC_6235.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'TUNA SALAD',
    price: 3,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-8.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'GREEK SALAD',
    price: 6,
    image: `${imageUrl}/DSC_6068.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'EGGPLANT DIP',
    price: 3,
    image: `${imageUrl}/DSC_6178.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'TOMATO WITH LEMON AND GARLIC ',
    price: 3,
    image: `${imageUrl}/DSC_6182.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'HUMMUS WITH LAMB',
    price: 3,
    image: `${imageUrl}/DSC_6047.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'HUMMUS',
    price: 3,
    image: `${imageUrl}/DSC_6114.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'COLESLAW',
    price: 4,
    image: `${imageUrl}/DSC_6111.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'CHILI HUMMUS',
    price: 3,
    image: `${imageUrl}/DSC_6134.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'CUCUMBER WITH YOGURT',
    price: 3,
    image: `${imageUrl}/DSC_6245.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'YOGURT',
    price: 3,
    image: `${imageUrl}/DSC_6245.JPG`,
  },
  {
    categorySlug: 'appetizers',
    name: 'BABAGANOUJ',
    price: 3,
    image: `${imageUrl}/DSC_6187.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'ROYAL HADRAMAWT MIX GRILL WITH RICE OR BREAD',
    price: 14,
    image: `${imageUrl}/DSC_6372.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'MIX GRILL ',
    price: 12,
    image: `${imageUrl}/DSC_6394.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'MIX GRILL',
    price: 7,
    image: `${imageUrl}/DSC_6309.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'LAMB KEBAB',
    price: 5,
    image: `${imageUrl}/DSC_6326.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'GRILLED LAMB CUBES',
    price: 6,
    image: `${imageUrl}/DSC_6309.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'HALAB KEBAB',
    price: 7,
    image: `${imageUrl}/DSC_9642.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'KASH KASH KEBAB',
    price: 7,
    image: `${imageUrl}/DSC_9703.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'ARAYESS (LAMB)',
    price: 5,
    image: `${imageUrl}/DSC_6364.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'LAMB KEBAB WITH RICE',
    price: 8,
    image: `${imageUrl}/283A9601.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'GRILLED LAMB CUBES WITH RICE',
    price: 9,
    image: `${imageUrl}/283A9601.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'CHICKEN KEBAB',
    price: 8,
    image: `${imageUrl}/DSC_6326.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'SHISH TAWOOQ',
    price: 6,
    image: `${imageUrl}/DSC_6286.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'ARAYESS (CHICKEN)',
    price: 5,
    image: `${imageUrl}/DSC_6364.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'CHICKEN KEBAB WITH RICE',
    price: 8,
    image: `${imageUrl}/283A9585.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'GRILLED CHICKEN',
    price: 9,
    image: `${imageUrl}/DSC_9596.JPG`,
  },
  {
    categorySlug: 'barbecue-dishes',
    name: 'SHISH TAWOOQ WITH RICE',
    price: 5,
    image: `${imageUrl}/283A9578.JPG`,
  },
  {
    categorySlug: 'main-dishes-chicken',
    name: '1/2 CHICKEN MANDY WITH RICE',
    price: 6,
    image: `${imageUrl}/DSC_8932.JPG`,
  },
  {
    categorySlug: 'main-dishes-chicken',
    name: '2 HALF CHICKEN MANDY WITH RICE',
    price: 12,
    image: `${imageUrl}/DSC_8932.JPG`,
  },
  {
    categorySlug: 'main-dishes-chicken',
    name: '1/2 CHICKEN KABSA WITH RICE',
    price: 7,
    image: `${imageUrl}/DSC_8937.JPG`,
  },
  {
    categorySlug: 'main-dishes-chicken',
    name: '2 HALF CHICKEN KABSA WITH RICE',
    price: 14,
    image: `${imageUrl}/DSC_8937.JPG`,
  },
  {
    categorySlug: 'main-dishes-chicken',
    name: '1/2 CHICKEN MADGHOUT WITH RICE',
    price: 7,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-53.JPG`,
  },
  {
    categorySlug: 'main-dishes-chicken',
    name: '2 HALF CHICKEN MADGHOUT WITH RICE',
    price: 13,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-53.JPG`,
  },
  {
    categorySlug: 'main-dishes-chicken',
    name: '1/2 GRILLED CHICKEN WITH RICE',
    price: 10,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-3 - Copy.JPG`,
  },
  {
    categorySlug: 'main-dishes-chicken',
    name: '2 HALF GRILLED CHICKEN WITH RICE',
    price: 13,
    image: noImage,
  },
  {
    categorySlug: 'main-dishes-chicken',
    name: 'CHICKEN MAQLUBA',
    price: 6,
    image: noImage,
  },
  {
    categorySlug: 'main-dishes-chicken',
    name: 'SPAGHETTI (CHICKEN)',
    price: 4,
    image: `${imageUrl}/DSC_7590.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB MANDY WITH RICE',
    price: 5,
    image: `${imageUrl}/DSC_8975.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: '2 LAMB MANDY WITH RICE REGULAR',
    price: 16,
    image: `${imageUrl}/DSC_8975.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB MANDY WITH RICE 1KG',
    price: 25,
    image: `${imageUrl}/DSC_9035.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB KABSA WITH RICE ',
    price: 7,
    image: `${imageUrl}/DSC_8975.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: '2 LAMB KABSA WITH RICE REGULAR',
    price: 10,
    image: `${imageUrl}/DSC_8975.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB KABSA WITH RICE 1/2 KG',
    price: 10,
    image: `${imageUrl}/DSC_9035.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB KABSA WITH RICE 1 KG',
    price: 20,
    image: `${imageUrl}/DSC_9035.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB MADGHOUT WITH RICE REGULAR',
    price: 8,
    image: `${imageUrl}/DSC_8958.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: '2 LAMB MADGHOUT WITH RICE REGULAR',
    price: 10,
    image: `${imageUrl}/DSC_8958.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB MADGHOUT WITH RICE 1/2 KG',
    price: 9,
    image: `${imageUrl}/DSC_9753.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB MADGHOUT WITH RICE 1KG',
    price: 20,
    image: `${imageUrl}/DSC_9753.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB HANEETH WITH RICE',
    price: 10,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-56 - Copy.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: '2 LAMB HANEETH WITH RICE REGULAR',
    price: 16,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-56 - Copy.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB HANEETH WITH RICE 1KG',
    price: 21,
    image: `${imageUrl}/A002.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB MAQLUBA WITH RICE',
    price: 8,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-146.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'LAMB BURMA',
    price: 9,
    image: `${imageUrl}/283A0257.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'SPAGHETTI (LAMB)',
    price: 4,
    image: `${imageUrl}/DSC_7590.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'SPAGHETTI (TOMATO SAUCE)',
    price: 2,
    image: `${imageUrl}/DSC_7590.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'MANDY RICE PLATE',
    price: 2,
    image: `${imageUrl}/283A9656.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'SPAGHETTI (NORMAL)',
    price: 2,
    image: `${imageUrl}/283A9652.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'MADGHOUT RICE PLATE',
    price: 3,
    image: `${imageUrl}/283A9649.JPG`,
  },
  {
    categorySlug: 'main-dishes-lamb',
    name: 'KABSA RICE PLATE',
    price: 10,
    image: `${imageUrl}/DSC_8975.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'ROYAL HADRAMAWT MIX SEAFOOD (GRILLED, FRIED, OVEN)',
    price: 16,
    image: `${imageUrl}/DSC_9520.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'MIX SEAFOOD (GRILLED, FRIED)',
    price: 13,
    image: `${imageUrl}/DSC_9635.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'GRILLED PRAWN',
    price: 7,
    image: `${imageUrl}/DSC_9542.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'FRIED PRAWN',
    price: 8,
    image: `${imageUrl}/DSC_9678.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'PRAWNS ESCALOPE',
    price: 7,
    image: `${imageUrl}/283A9610.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'CLAYPOT FILLET',
    price: 5,
    image: `${imageUrl}/DSC_9706.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'CLAYPOT PRAWNS',
    price: 6,
    image: `${imageUrl}/DSC_7501.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'CLAYPOT CALAMARI',
    price: 5,
    image: `${imageUrl}/DSC_9737.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'CLAYPOT FISH',
    price: 5,
    image: `${imageUrl}/DSC_9736.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'FRIED FISH',
    price: 6,
    image: `${imageUrl}/DSC_9586.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'OVEN BAKED FISH',
    price: 8,
    image: `${imageUrl}/DSC_9553.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'GRILLED FISH',
    price: 8,
    image: `${imageUrl}/DSC_9670.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'GRILLED/FRIED FISH STEAK',
    price: 6,
    image: `${imageUrl}/DSC_9721.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'FRIED/GRILLED FILLET FISH',
    price: 6,
    image: `${imageUrl}/DSC_9534.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'FRIED CALAMARI',
    price: 5,
    image: `${imageUrl}/DSC_9674.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'GRILLED FISH STEAK WITH RICE',
    price: 5,
    image: `${imageUrl}/DSC_9623.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'FRIED FISH WITH RICE',
    price: 9,
    image: `${imageUrl}/DSC_9586.JPG`,
  },
  {
    categorySlug: 'sea-food',
    name: 'FRIED/GRILLED FILLET FISH WITH RICE',
    price: 6,
    image: `${imageUrl}/DSC_9665.JPG`,
  },
  {
    categorySlug: 'arabian-bread',
    name: 'MULLAWAH ',
    price: 3,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-45.JPG`,
  },
  {
    categorySlug: 'arabian-bread',
    name: 'MULLAWAH ',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-47(1).JPG`,
  },
  {
    categorySlug: 'arabian-bread',
    name: 'MULLAWAH ',
    price: 1,
    image: `${imageUrl}/283A0253.JPG`,
  },
  {
    categorySlug: 'arabian-bread',
    name: 'FRISH ARABIAN BREAD ',
    price: 2,
    image: `${imageUrl}/283A0169.JPG`,
  },
  {
    categorySlug: 'arabian-bread',
    name: 'MULLAWAH RATEB',
    price: 2,
    image: `${imageUrl}/283A0253.JPG`,
  },
  {
    categorySlug: 'arabian-bread',
    name: 'MULLAWAH WITH EGGS',
    price: 3,
    image: `${imageUrl}/283A0253.JPG`,
  },
  {
    categorySlug: 'hot-soups',
    name: 'LENTIL SOUP',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-69.JPG`,
  },
  {
    categorySlug: 'hot-soups',
    name: 'VEGETABLES SOUP',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-62.JPG`,
  },
  {
    categorySlug: 'hot-soups',
    name: 'CHICKEN SOUP',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-65(1).JPG`,
  },
  {
    categorySlug: 'hot-soups',
    name: 'MUSHROOM SOUP',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-66.JPG`,
  },
  {
    categorySlug: 'hot-soups',
    name: 'MOROCCAN HARIRAH SOUP',
    price: 2,
    image: `${imageUrl}/A007.JPG`,
  },
  {
    categorySlug: 'sandwiches',
    name: 'LAMB KEBAB SANDWITCH',
    price: 5,
    image: `${imageUrl}/283A0245.JPG`,
  },
  {
    categorySlug: 'sandwiches',
    name: 'GRILLED LAMB CUBES SANDWITCH',
    price: 5,
    image: noImage,
  },
  {
    categorySlug: 'sandwiches',
    name: 'CHICKEN KEBAB SANDWITCH',
    price: 5,
    image: `${imageUrl}/283A0250.JPG`,
  },
  {
    categorySlug: 'sandwiches',
    name: 'SHISH TAWOOQ SANDWITCH',
    price: 5,
    image: noImage,
  },
  {
    categorySlug: 'sandwiches',
    name: 'CHICKEN MAYONNAISE',
    price: 5,
    image: `${imageUrl}/283A0222.JPG`,
  },
  {
    categorySlug: 'sandwiches',
    name: 'CAMEL MEAT SANDWITCH',
    price: 5,
    image: noImage,
  },
  {
    categorySlug: 'sandwiches',
    name: 'CHEESE & TOMATO',
    price: 2,
    image: `${imageUrl}/283A0222.JPG`,
  },
  {
    categorySlug: 'sandwiches',
    name: 'CHICKEN CHEESE',
    price: 4,
    image: `${imageUrl}/283A0225.JPG`,
  },
  {
    categorySlug: 'sandwiches',
    name: 'ROLLS (MEAT/CHICKEN/FISH)',
    price: 5,
    image: noImage,
  },
  {
    categorySlug: 'sandwiches',
    name: 'EGG SANDWITCH',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'TEA CUP',
    price: 2,
    image: `${imageUrl}/DSC_9800.JPG`,
  },
  {
    categorySlug: 'beverages',
    name: 'ARABIC TEA WITH MINT',
    price: 3,
    image: `${imageUrl}/DSC_9790.JPG`,
  },
  {
    categorySlug: 'beverages',
    name: 'POT OF TEA',
    price: 3,
    image: `${imageUrl}/DSC_9790.JPG`,
  },
  {
    categorySlug: 'beverages',
    name: 'ADANI TEA (TEA TAREK)',
    price: 2,
    image: `${imageUrl}/DSC_9805.JPG`,
  },
  {
    categorySlug: 'beverages',
    name: 'POT OF TEA WITH MILK (ADANI)',
    price: 3,
    image: `${imageUrl}/DSC_9808.JPG`,
  },
  {
    categorySlug: 'beverages',
    name: 'SOMALI COFFEE',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'NESCAFE',
    price: 3,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'TURKISH COFFEE',
    price: 3,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'ICE LEMON TEA',
    price: 2.5,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'MILO',
    price: 3,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'MOUNTAINDEW',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'BARBICAN',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'COCACOLA',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'PEPSI',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'MIRINDA (STRAWBERRY / ORANGE)',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: '7UP',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: '100PLUS',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'SPRITE',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'MINERAL WATER',
    price: 1,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'MINERAL WATER',
    price: 0.5,
    image: noImage,
  },
  {
    categorySlug: 'beverages',
    name: 'LEMON TEA (HOT)',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'ROYAL HADRAMAWT COCKTAIL',
    price: 'Royal Hadramawt Flamingo Hotel-126 - Copy(1)',
    image: noImage,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'ARAISEE',
    price: 4,
    image: `${imageUrl}/283A0194.JPG`,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'COCKTAIL JUICE ',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-105(1).JPG`,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'GRAPE JUICE ',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-118.JPG`,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'JAMAICA (PINEAPPLE WITH ORANGE) JUICE',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'STRAWBERRY JUICE',
    price: 2,
    image: `${imageUrl}/283A9686.JPG`,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'PAPAYA JUICE ',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'HONEYDEW MELON SHAKE',
    price: 2.5,
    image: noImage,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'MANGO SHAKE',
    price: 2.5,
    image: `${imageUrl}/283A9674.JPG`,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'BANANA SHAKE ',
    price: 2.5,
    image: noImage,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'MANGO JUICE',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-106(1).jpg.JPG`,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'APPLE JUICE',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'ORANGE JUICE ',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'CARROT JUICE',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'PINEAPPLE JUICE',
    price: 3,
    image: `${imageUrl}/283A9687.JPG`,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'WATERMELON JUICE',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-114(1).JPG`,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'LEMON WITH MINT JUICE ',
    price: 2,
    image: `${imageUrl}/283A9702.JPG`,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'LEMON JUICE ',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-110(1).JPG`,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'VIMTO',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'CHOCOLATE',
    price: 2,
    image: `${imageUrl}/283A9696.JPG`,
  },
  {
    categorySlug: 'fresh-juices',
    name: 'JUICES',
    price: 5,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'MIX FRUITS ',
    price: 4,
    image: `${imageUrl}/DSC_8908.JPG`,
  },
  {
    categorySlug: 'desserts',
    name: 'MIX FRUITS ',
    price: 2.5,
    image: `${imageUrl}/283A0200.JPG`,
  },
  {
    categorySlug: 'desserts',
    name: 'ROYAL HADRAMAWT  MASOOB',
    price: 3,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'BANANA MASOOB',
    price: 3,
    image: `${imageUrl}/283A0215.JPG`,
  },
  {
    categorySlug: 'desserts',
    name: 'HONEY MASOOB',
    price: 3,
    image: `${imageUrl}/283A0218.JPG`,
  },
  {
    categorySlug: 'desserts',
    name: 'DATES MASOOB',
    price: 3,
    image: `${imageUrl}/283A0204.JPG`,
  },
  {
    categorySlug: 'desserts',
    name: 'BAQLAWA ',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-130.JPG`,
  },
  {
    categorySlug: 'desserts',
    name: 'KUNAFA',
    price: 2,
    image: `${imageUrl}/Royal Hadramawt Flamingo Hotel-136.JPG`,
  },
  {
    categorySlug: 'desserts',
    name: 'MIX desserts ',
    price: 3,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'MANGO/BANANA TART',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'BASBOSAH',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'FRUIT STRODDE/ STROWBERY SAUCE',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'FRUIT CRUMBLE/ CUSTARD SAUCE',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'PINEAPPLE CRUMBLE /CUSTARD',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'APPLE CAKE WITH BUTTER SCOTCH SAUCE',
    price: 3,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'special order',
    price: 3,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'WHOLE LAMB FOR AQEQAH',
    price: 0,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'WHOLE LAMB MANDY WITH RICE',
    price: 0,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'HALF LAMB MANDY WITH RICE',
    price: 0,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'QUARTER LAMB MANDY WITH RICE',
    price: 0,
    image: noImage,
  },
  {
    categorySlug: 'desserts',
    name: 'ROYAL MIX FRUITS',
    price: 0,
    image: `${imageUrl}/DSC_6554.JPG`,
  },
  {
    categorySlug: 'coffee',
    name: 'COFFEE LATTE',
    price: 2.5,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'AMERICANO',
    price: 2.5,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'MOCHACCINO',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'CAPPUCCINO',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'MASALA LATTE',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'HOT CHOCOLATE',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'ENGLISH TEA',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'SOMALI TEA',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'LEMON TEA',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'MASALA TEA',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'DAWA TEA',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'CARAMEL MACIATO',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'COFFEE ( BLACK /WHITE )',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'coffee',
    name: 'EXPRESSO',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'ice-cream',
    name: 'CHOCOLATE ICE-CREAM',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'ice-cream',
    name: 'STRAWBERRY ICE-CREAM',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'ice-cream',
    name: 'VANILLA ICE-CREAM',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'ice-cream',
    name: 'APPLE',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'ice-cream',
    name: 'MUSTYCIO',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'ice-cream',
    name: 'MANGO',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'ice-cream',
    name: 'ICE CREAM',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'CHICKEN PIES',
    price: 2,
    image: `${imageUrl}/283A0156.JPG`,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'CAMEL STEAK PIES',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'SAUSAGE ROLL',
    price: 1.5,
    image: `${imageUrl}/283A0165.JPG`,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'PLAIN CROISSANT',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'ALMOND CROISSANT',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'CHOCOLATE CROISSANT',
    price: 1.5,
    image: `${imageUrl}/283A0160.JPG`,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'BASBOUSA',
    price: 1,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'CARROT CAKE',
    price: 2.5,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'WHITE FOREST CAKE',
    price: 2.5,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'CHOCOLATE CAKE',
    price: 2.5,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'BANANA/LEMON MUFFIN',
    price: 1,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'ORANGE CAKE',
    price: 2.5,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'TEA SCONE',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'COOKIES',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'VANILLA CAKE',
    price: 2.5,
    image: noImage,
  },
  {
    categorySlug: 'pies-pastry',
    name: 'MARHABA ASSORTED CAKE',
    price: 1.5,
    image: noImage,
  },
  {
    categorySlug: 'snacks',
    name: 'SAMOSAS - MEAT/FISH',
    price: 1,
    image: `${imageUrl}/maxresdefault.JPG`,
  },
  {
    categorySlug: 'snacks',
    name: 'MINI MANDAZI',
    price: 1,
    image: noImage,
  },
  {
    categorySlug: 'snacks',
    name: 'PAN CAKES',
    price: 1,
    image: noImage,
  },
  {
    categorySlug: 'snacks',
    name: 'FRENCH TOAST',
    price: 1,
    image: noImage,
  },
  {
    categorySlug: 'snacks',
    name: 'VEGETABLE SPRING ROLLS',
    price: 5,
    image: noImage,
  },
  {
    categorySlug: 'snacks',
    name: 'FISH CAKE/HERBED MAYONNAISE',
    price: 4.5,
    image: noImage,
  },
  {
    categorySlug: 'snacks',
    name: 'PRETTY KEBABS',
    price: 1,
    image: noImage,
  },
  {
    categorySlug: 'snacks',
    name: 'SPRING ROLLS CHICKEN',
    price: 5,
    image: noImage,
  },
  {
    categorySlug: 'snacks',
    name: 'VEGETABLE BHAJIA/ GRALIC',
    price: 1,
    image: noImage,
  },
  {
    categorySlug: 'burgers',
    name: 'CHICKEN BURGER',
    price: 5,
    image: `${imageUrl}/IMG_0532.jpg.JPG`,
  },
  {
    categorySlug: 'burgers',
    name: 'CAMEL MEAT BURGER',
    price: 5,
    image: `${imageUrl}/IMG_0532.jpg.JPG`,
  },
  {
    categorySlug: 'burgers',
    name: 'VEGETABLE BURGER',
    price: 5,
    image: `${imageUrl}/IMG_0532.jpg.JPG`,
  },
  {
    categorySlug: 'burgers',
    name: 'CHICKEN CHEESE BURGER',
    price: 5,
    image: `${imageUrl}/IMG_0532.jpg.JPG`,
  },
  {
    categorySlug: 'burgers',
    name: 'FISH BURGER',
    price: 5,
    image: `${imageUrl}/IMG_0532.jpg.JPG`,
  },
  {
    categorySlug: 'burgers',
    name: 'EGG BURGER',
    price: 5,
    image: `${imageUrl}/IMG_0532.jpg.JPG`,
  },
  {
    categorySlug: 'burgers',
    name: 'KING SIZE BURGER',
    price: 7,
    image: `${imageUrl}/IMG_0532.jpg.JPG`,
  },
  {
    categorySlug: 'pizza',
    name: 'CHICKEN MUSHROOM',
    price: 8,
    image: `${imageUrl}/IMG_3650.jpg.JPG`,
  },
  {
    categorySlug: 'pizza',
    name: 'CAMEL DELUXE',
    price: 7,
    image: `${imageUrl}/IMG_3650.jpg.JPG`,
  },
  {
    categorySlug: 'pizza',
    name: 'HAWAIN PIZZA',
    price: 7,
    image: `${imageUrl}/IMG_3650.jpg.JPG`,
  },
  {
    categorySlug: 'pizza',
    name: 'INDIANA PIZZA',
    price: 7,
    image: `${imageUrl}/IMG_3650.jpg.JPG`,
  },
  {
    categorySlug: 'pizza',
    name: 'CHEESE PIZZA',
    price: 7,
    image: `${imageUrl}/IMG_3650.jpg.JPG`,
  },
  {
    categorySlug: 'pizza',
    name: 'BBQ PIZZA',
    price: 7,
    image: `${imageUrl}/IMG_3650.jpg.JPG`,
  },
  {
    categorySlug: 'pizza',
    name: 'FISH PIZZA',
    price: 7,
    image: `${imageUrl}/IMG_3650.jpg.JPG`,
  },
  {
    categorySlug: 'pizza',
    name: 'MARGHERITTA PIZZA',
    price: 7,
    image: `${imageUrl}/IMG_3650.jpg.JPG`,
  },
  {
    categorySlug: 'pizza',
    name: 'PEPPERONI PIZZA',
    price: 7,
    image: `${imageUrl}/IMG_3650.jpg.JPG`,
  },
  {
    categorySlug: 'pizza',
    name: 'CHICKEN TIKKA PIZZA',
    price: 7,
    image: `${imageUrl}/IMG_3650.jpg.JPG`,
  },
  {
    categorySlug: 'indian-food',
    name: 'JEERA RICE',
    price: 2,
    image: `${imageUrl}/283A2886.JPG`,
  },
  {
    categorySlug: 'indian-food',
    name: 'VEGETABLE RICE',
    price: 2.5,
    image: `${imageUrl}/283A0230.JPG`,
  },
  {
    categorySlug: 'indian-food',
    name: 'STEAMED RICE',
    price: 2,
    image: `${imageUrl}/283A2879.JPG`,
  },
  {
    categorySlug: 'indian-food',
    name: 'FRIED RICE',
    price: 2.5,
    image: `${imageUrl}/283A2894.JPG`,
  },
  {
    categorySlug: 'chapati',
    name: 'SADA CHAPATI',
    price: 1,
    image: `${imageUrl}/283A2897.JPG`,
  },
  {
    categorySlug: 'chapati',
    name: 'PARATHA',
    price: 1.5,
    image: `${imageUrl}/283A2901.JPG`,
  },
  {
    categorySlug: 'chapati',
    name: 'EGG PARATHA',
    price: 2,
    image: `${imageUrl}/283A2903.JPG`,
  },
  {
    categorySlug: 'chapati',
    name: 'BUTTER CHAPATI',
    price: 3,
  },
  {
    categorySlug: 'chapati',
    name: 'ALO PARATHA',
    price: 1.5,
    image: `${imageUrl}/283A2908.JPG`,
  },
  {
    categorySlug: 'chapati',
    name: 'CHEESE PARATHA',
    price: 3,
    image: `${imageUrl}/283A2909.JPG`,
  },
  {
    categorySlug: 'curry',
    name: 'CHICKEN CURRY',
    price: 7,
    image: `${imageUrl}/283A2828.JPG`,
  },
  {
    categorySlug: 'curry',
    name: 'FISH CURRY',
    price: 7,
    image: `${imageUrl}/283A2849.JPG`,
  },
  {
    categorySlug: 'curry',
    name: 'MUTTON CURRY',
    price: 8,
    image: `${imageUrl}/283A2855.JPG`,
  },
  {
    categorySlug: 'curry',
    name: 'EGG CURRY',
    price: 6,
    image: `${imageUrl}/283A2834.JPG`,
  },
  {
    categorySlug: 'curry',
    name: 'PALAK PANEER',
    price: 8,
  },
  {
    categorySlug: 'curry',
    name: 'BHINDI FRY',
    price: 6,
    image: `${imageUrl}/283A2868.JPG`,
  },
  {
    categorySlug: 'curry',
    name: 'DAAL FRY',
    price: 3,
    image: `${imageUrl}/283A2877.JPG`,
  },
  {
    categorySlug: 'curry',
    name: 'MEAT CURRY',
    price: 7,
    image: `${imageUrl}/283A2855.JPG`,
  },
  {
    categorySlug: 'curry',
    name: 'FRY CHICKEN',
    price: 7,
    image: noImage,
  },
  {
    categorySlug: 'curry',
    name: 'BUTTER CHICKEN',
    price: 10,
    image: `${imageUrl}/283A2841.JPG`,
  },
  {
    categorySlug: 'curry',
    name: 'MATTAR PANEER',
    price: 8,
    image: noImage,
  },
  {
    categorySlug: 'curry',
    name: 'ALOO PALAK',
    price: 6,
    image: `${imageUrl}/283A2859.JPG`,
  },
  {
    categorySlug: 'curry',
    name: 'CHOLA MASALA',
    price: 6,
    image: `${imageUrl}/283A2863.JPG`,
  },
  {
    categorySlug: 'side-dish',
    name: 'LASSIE',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'side-dish',
    name: 'SALAD',
    price: 2,
    image: `${imageUrl}/283A9631.JPG`,
  },
  {
    categorySlug: 'side-dish',
    name: 'YOGURT',
    price: 2,
    image: `${imageUrl}/DSC_6245.JPG`,
  },
  {
    categorySlug: 'sweet',
    name: 'CARROT HALWA',
    price: 1,
    image: noImage,
  },
  {
    categorySlug: 'sweet',
    name: 'COCONUT SWEET',
    price: 1,
    image: noImage,
  },
  {
    categorySlug: 'sweet',
    name: 'KAJUKATLI',
    price: 1,
    image: noImage,
  },
  {
    categorySlug: 'ethiopian-food',
    name: 'BEYAYNETU',
    price: 7,
    image: `${imageUrl}/IMG_0442.jpg.JPG`,
  },
  {
    categorySlug: 'ethiopian-food',
    name: 'TIBS WITH INJERA',
    price: 10,
    image: `${imageUrl}/IMG_0442.jpg.JPG`,
  },
  {
    categorySlug: 'ethiopian-food',
    name: 'DORO WAT',
    price: 11,
    image: `${imageUrl}/IMG_0442.jpg.JPG`,
  },
  {
    categorySlug: 'ethiopian-food',
    name: 'AYIB BE GOMEN',
    price: 8,
    image: `${imageUrl}/IMG_0442.jpg.JPG`,
  },
  {
    categorySlug: 'ethiopian-food',
    name: 'ALL TEST IN ONE PLATE',
    price: 12,
    image: `${imageUrl}/IMG_0442.jpg.JPG`,
  },
  {
    categorySlug: 'ethiopian-food',
    name: 'YEMISIR WOT',
    price: 7,
    image: `${imageUrl}/IMG_0442.jpg.JPG`,
  },
  {
    categorySlug: 'ethiopian-food',
    name: 'SHIRO WAT',
    price: 7,
    image: `${imageUrl}/IMG_0442.jpg.JPG`,
  },
  {
    categorySlug: 'ethiopian-food',
    name: 'SEGA WAT',
    price: 10,
    image: `${imageUrl}/IMG_0442.jpg.JPG`,
  },
  {
    categorySlug: 'ethiopian-food',
    name: 'FIR-FIR INJERA',
    price: 10,
    image: `${imageUrl}/IMG_0442.jpg.JPG`,
  },
  {
    categorySlug: 'breakfast',
    name: 'EGGS',
    price: 2,
    image: `${imageUrl}/DSC_7389.JPG`,
  },
  {
    categorySlug: 'breakfast',
    name: 'PANCAKE WITH HONEY',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'breakfast',
    name: 'LIVER WITH INJERA',
    price: 5,
    image: `${imageUrl}/DSC_7445.JPG`,
  },
  {
    categorySlug: 'breakfast',
    name: 'FULL EGYPTIAN BEANS WITH CHAPATI',
    price: 3,
    image: noImage,
  },
  {
    categorySlug: 'breakfast',
    name: 'FRENCH TOAST',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'breakfast',
    name: 'SHORBA',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'breakfast',
    name: 'WET FRY MEAT',
    price: 5,
    image: noImage,
  },
  {
    categorySlug: 'breakfast',
    name: 'PLAN TOAST WITH JAM AND BUTTER',
    price: 2,
    image: noImage,
  },
  {
    categorySlug: 'breakfast',
    name: 'BEANS SERVED WITH MAHAMRI CHAPATI',
    price: 3,
    image: noImage,
  },
  {
    categorySlug: 'breakfast',
    name: 'DANISH PASTRY',
    price: 3,
    image: noImage,
  },
  {
    categorySlug: 'breakfast',
    name: 'CROISSANT',
    price: 3,
    image: noImage,
  },
  {
    categorySlug: 'breakfast',
    name: 'BUFFET BREAKFAST',
    price: 7,
    image: noImage,
  },
  {
    categorySlug: 'special-order',
    name: 'WHOLE LAMB FOR AQEQAH',
    price: 0,
    image: noImage,
  },
  {
    categorySlug: 'special-order',
    name: 'HALF LAMB MANDY WITH RICE',
    price: 0,
    image: noImage,
  },
  {
    categorySlug: 'special-order',
    name: 'ROYAL MIX FRUITS',
    price: 0,
    image: `${imageUrl}/DSC_6554.JPG`,
  },
  {
    categorySlug: 'special-order',
    name: 'WHOLE LAMB MANDY WITH RICE',
    price: 0,
    image: noImage,
  },
  {
    categorySlug: 'special-order',
    name: 'QUARTER LAMB MANDY WITH RICE',
    price: 0,
    image: noImage,
  },
]
